<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Pythonwifi-dev] [Bug #16382] IndexError: string index out of range	with scan()
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/pythonwifi-dev/2009-October/index.html" >
   <LINK REL="made" HREF="mailto:pythonwifi-dev%40lists.berlios.de?Subject=Re%3A%20%5BPythonwifi-dev%5D%20%5BBug%20%2316382%5D%20IndexError%3A%20string%20index%20out%20of%20range%0A%09with%20scan%28%29&In-Reply-To=%3C200910310138.n9V1cwj7004930%40unicorn.berlios.de%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000002.html">
   
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Pythonwifi-dev] [Bug #16382] IndexError: string index out of range	with scan()</H1>
    <B>admin at berlios.de</B> 
    <A HREF="mailto:pythonwifi-dev%40lists.berlios.de?Subject=Re%3A%20%5BPythonwifi-dev%5D%20%5BBug%20%2316382%5D%20IndexError%3A%20string%20index%20out%20of%20range%0A%09with%20scan%28%29&In-Reply-To=%3C200910310138.n9V1cwj7004930%40unicorn.berlios.de%3E"
       TITLE="[Pythonwifi-dev] [Bug #16382] IndexError: string index out of range	with scan()">admin at berlios.de
       </A><BR>
    <I>Sat Oct 31 02:38:58 CET 2009</I>
    <P><UL>
        <LI>Previous message: <A HREF="000002.html">[Pythonwifi-dev] [Bug #16382] IndexError: string index out of range	with scan()
</A></li>
        
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#3">[ date ]</a>
              <a href="thread.html#3">[ thread ]</a>
              <a href="subject.html#3">[ subject ]</a>
              <a href="author.html#3">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Bug #16382, was updated on 2009-Oct-29 03:21
Here is a current snapshot of the bug.

Project: Python-WIFI
Category: iwlibs
Status: Open
Resolution: None
Bug Group: None
Priority: 5
Submitted by: virusx
Assigned to : robinson
Summary: IndexError: string index out of range with scan()

Details: Hello,
I've download pythonwifi this week and I've an Index Error with this code :


from pythonwifi.iwlibs import Wireless, getNICnames
wifi = Wireless('wlan1')

networks = wifi.scan();
for network in enumerate(networks):
 print '%s : %s/100'%(network[1].essid, network[1].quality.quality)
 print network

This comes from me or the library ?



For detailed info, follow this link:
<A HREF="http://developer.berlios.de/bugs/?func=detailbug&amp;bug_id=16382&amp;group_id=7134">http://developer.berlios.de/bugs/?func=detailbug&amp;bug_id=16382&amp;group_id=7134</A>

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000002.html">[Pythonwifi-dev] [Bug #16382] IndexError: string index out of range	with scan()
</A></li>
	
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#3">[ date ]</a>
              <a href="thread.html#3">[ thread ]</a>
              <a href="subject.html#3">[ subject ]</a>
              <a href="author.html#3">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/pythonwifi-dev">More information about the Pythonwifi-dev
mailing list</a><br>
</body></html>
